{{- if and .Values.rbac.create .Values.clusterScoped -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "skupper.fullname" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "skupper.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "skupper.fullname" . }}
{{- end }}
