apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skupper.fullname" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "skupper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "skupper.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "skupper.serviceAccountName" . }}
      # Prevent kubernetes from injecting env vars for grant service
      # as these then collide with those that actually configure the
      # controller:
      enableServiceLinks: false
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/controller"]
          args:
            {{- include "skupper.args" . | nindent 12 }}
          env:
          - name: SKUPPER_CONFIG_SYNC_IMAGE
            value:  "{{ .Values.configSyncImage.repository }}:{{ .Values.configSyncImage.tag | default .Chart.AppVersion }}"
          - name: SKUPPER_ROUTER_IMAGE
            value:  "{{ .Values.routerImage.repository }}:{{ .Values.routerImage.tag | default "main" }}"
          {{- if not .Values.clusterScoped }}
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- end }}
          volumeMounts:
            - name: tls-credentials
              mountPath: /etc/controller
      volumes:
      - name: tls-credentials
        emptyDir: {}
