{{- if and .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ if .Values.clusterScoped -}} ClusterRoleBinding {{- else }} RoleBinding {{- end }}
metadata:
  name: {{ include "skupper.fullname" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "skupper.serviceAccountName" . }}
  {{- if .Values.clusterScoped }}
  namespace: {{ .Release.Namespace }} {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ if .Values.clusterScoped -}} ClusterRole {{- else }} Role {{- end }}
  name: {{ include "skupper.fullname" . }}
{{- end }}
