{{- if and .Values.rbac.create (not .Values.clusterScoped) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "skupper.fullname" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "skupper.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "skupper.fullname" . }}
{{- end }}
