{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skupper.serviceAccountName" . }}
  labels:
    {{- include "skupper.labels" . | nindent 4 }}
{{- end }}
