apiVersion: v2
name: skupper
description: Install skupper
type: application
version: 0.2.0-devel
appVersion: "v2-latest"
keywords:
  - skupper
  - controller
sources:
  - https://github.com/skupperproject/skupper
dependencies:
  - name: crds
    version: "0.0.0"
    condition: crds.enabled
